### ISSUE TITLE
Create Updated POQ Unity SDK

### ISSUE THREAD

**Issue by bmcilw1** [weiks/quarters-unity-sdk#1]
# Background

## POQ Company

POQ offers simple web2 to web3 integration, including social logins, game currencies, and NFTs. Our flagship product is [Quarters](https://invest.poq.gg/), the first interoperable gaming token. With POQ, both developers and players get web2 convenience combined with the power of Web3.

Some notable POQ highlights:
* Founded by a 12 year-old ([watch Meet the Drapers](https://www.youtube.com/watch?v=CtdaxgX1LKo))
* [The first and only No-Action letter given by the US SEC for a blockchain token](https://www.coindesk.com/sec-clears-blockchain-gaming-startup-to-sell-quarters-tokens/) 
* POQ's [patented "Zero Click" technology](https://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=1&f=G&l=50&co1=AND&d=PTXT&s1=11189131&OS=11189131&RS=11189131) for use of blockchain in video games
* [Partnered with Klaytn](https://medium.com/klaytn/poq-partners-with-klaytn-launching-the-first-ever-metaverse-gaming-token-a08a7bb87677) and other major blockchains to provide access to over $1B in grant funding

## POQ Oauth API

Developers can access players wallets, and send and receive Quarters and NFTs, and even create NFTs and collections, with POQ's Ouath API. See the [technical documentation for the Oauth API](https://docs.poq.gg).

## Unity SDK

The Unity SDK provides a convenient wrapper for the POQ Ouath API and UI for both login and in-app purchases. Since the current version was developed about 24 months ago, we now need to updated the SDK to: 
(1) newer versions of Unity
(2) switch from IAP to Apple Pay
(3) support the new NFT functionality within our API  (*immediate next step*)
(4) extend beyond mobile to PC and console (*future*)
(5) plan how to extend to be an Unreal SDK (*future*)

**You can see the current status of the project in this repo on the `develop` branch. This is the most up-to-date version of the codebase.**

## Beyond this project

For the information of those working on this project, our near-term plans for POQ core APIs include the following

1. The creation of a GraphQL API duplicating the existing OAuth REST API (confirmed)
2. The removal of our REST API in favor of the new GraphQL version (likely, but not confirmed)
3. The addition of more fields and mutations to the API as more games use our system
4. Another look at our NFT API to create a higher-level API that's even easier to use
5. Rigorous, extensive, and unbalanced load requirements to all our systems as the Quarters system continues to grow into a large heavily used system with 10-100 million+ users

# Project

## Prework

Before work is begun, we need to be sure the scope is well understood with all checkpoints below, plus regular reporting expectations. Perhaps even more important than the original deliveries would be a firm commitment to providing timely support on an ongoing basis as both our systems and the Unity platform continue to evolve.

The current [docs for POQ Game Developers](https://github.com/weiks/poq-docs) explain the current version of the POQ core API that we need to wrap in the SDK. This needs to be compared with the old version of the SDK in this repo. It is up to the team working on this to decide how much (if any) of the old code in this repo will be used in the new version. I will assume a full rewrite for the write-up below for the sake of comprehensive clarifying of scope.

The following specifies expectations of "done" for each version below. Work on a new version should not begin until receiving sign-off on all items for the previous version.

## Definition of Done
- [ ] An architectural doc specifying proposed implementation decisions for sign off prior to code
- [ ] (2.0+) An design doc specifying proposed UI/UX for sign-off prior to code. We may provide this for you.
- [ ] Code for each item needed for all the functionality in the scope
- [ ] Unit and integration tests that demonstrate the correctness of the code
- [ ] (2.0+) e2e tests of UI components
- [ ] A deployment of this version of the SDK internally
- [ ] An example of using all SDK functions from the internally deployed SDK in a separate Unity project
- [ ] Documentation for how to use all functions for the benefit of other game developers trying to use the SDK. These may be assumed to be familiar with Unity, but not POQ or Quarters. Documentation should be written first-hand while linking heavily to existing POQ docs.
- [ ] Approval of all written code and non-code artifacts via Pull Request
- [ ] A demo of all the above to the POQ team
- [ ] (1.0+) A deployment of this version of the SDK to our external users
- [ ] (1.0+) Support for the new deployment to our external users, as requested and approved by POQ

## Version 0.1

The checkpoint is to create a new repo targeting the current version of Unity and implement the Authentication routes for the POQ system. The ONLY route that should be wrapped at this stage is the authentication route.

## Version 1.0

When we get a working sign-on and deployment, it is then time to add functionality to cover the rest of the endpoints in the OAuth API that focus on our native Quarters token ONLY, plus all auth endpoints. These are described in the [docs for POQ Game Developers](https://github.com/weiks/poq-docs). This version should be feature-complete and ready for use of all the endpoints related to the core Quarters token and management.

## Version 1.1

The next focus is adding support for our NFT endpoints, plus all the above. These are described in the [docs for POQ Game Developers](https://github.com/weiks/poq-docs). This version should be feature-complete and ready for use of all the endpoints related to NFTs. All endpoints described in the external POQ Docs should be wrapped at this point.

## Version 2.0

The next phase should build on top of the wrapped SDK and provide white-labeled UI components as an added convenience for our external game developers. The only code dependency for these components should be the POQ SDK and other minor UI dependencies. The first component that should be created is a generic Login component. This should make it easy for games to add their own branding to this as well as customize styling.

## Version 2.1

The next component is to add white-labeled UI support for purchasing Quarters.

## Version 2.2

The next component would be to add white-labeled UI support for interacting with the POQ prize store.

**Comment by weiks** [comment]
Example project: https://github.com/weiks/slot-invader
Demo: https://youtu.be/tJweRI-M4Go
Demo (new): https://youtu.be/fZ5N85-5Oeg

How to videos 
[IOS 1](https://www.youtube.com/watch?v=YJU192xItO0) * [IOS 2](https://youtu.be/uN-jabJudDQ) * [IOS 3](https://youtu.be/pJDFk7zJpNU) * [IOS 4](https://youtu.be/ltYgQwfIOlk) 
[Android 1](https://youtu.be/ltYgQwfIOlk) * [Android 2](https://youtu.be/82m2FTXy9cI) 
[Playfab IAP 1](https://youtu.be/tEH3nh-7-tw) * [Playfab IAP 2](https://youtu.be/IFkBRFeRb8c) * [Playfab IAP 3](https://youtu.be/tEH3nh-7-tw) * [Playfab IAP 4](https://youtu.be/AE6ZefYB10M) * [IAP 5](https://www.youtube.com/watch?v=F2R9otC4agI)

[Sign up - old](https://youtu.be/hxyYOSmfFHc)

**Comment by bmcilw1** [comment]
Buy URL: https://www.poq.gg/buy
Redirect URI: 

TODO: Pass UID as URL parameter, display Gamer Tag for the current user
