### ISSUE TITLE
[Bug-Minor] Documentation for API calls 

### ISSUE THREAD

**Issue by paulofer85** [weiks/quarters-unity-sdk#14]
Unity team found that:
1. we should check that documentation covers all API calls: Majority of public API methods are not covered in the documentation. Consider creating a separate documentation page dedicated solely for the C# API.
2. we should check that documentation is clear and contains no typos: Single-page documentation with setup, API and other details is difficult to follow and navigate
3. Check if public facing source code is summarized / commented

Actions to take:
1. Adding documentation and comments on methods (in `.cs`  and `.md` files) .
2. Adding a single-page documentation for API calls (`README-Api.md` was added).
4. Have a separate documentation file for API Calls

**Comment by bmcilw1** [comment]
done
