### ISSUE TITLE
[Bug-minor] GetAvatar

### ISSUE THREAD

**Issue by paulofer85** [weiks/quarters-unity-sdk#17]
### Description:
Unity found that `GetAvatar`:
-- Returns an 8x8 texture which seems to be a placeholder. If the feature is work-in-progress, please consider changing the access modifier from public to internal.

-- OnError callback action uses inconsistent parameter types compared to other APIs. Other callbacks utilize <string> while this one makes use of < Error >.

### Actions to take:
We decided to remove `GetAvatar` because right now there is no need to use it.

**Comment by unitydevelopers-greg** [comment]
This solution is now merged
