### ISSUE TITLE
[Cleanup] Add Unit Tests for key classes

### ISSUE THREAD

**Issue by bmcilw1** [weiks/quarters-unity-sdk#4]
## Background

Our latest work is located in the `develop` branch. Currently, the SDK does not have any tests. We need to add some basic testing to help validate the C# code.

We want to add unit tests for the [main Quarters class](https://github.com/weiks/quarters-unity-sdk/blob/develop/Assets/QuartersSDK/Scripts/Quarters.cs). After we get this we can investigate adding unit testing to other files as well as needed.

To do this, we may need to factor out the Unity runtime dependencies (via dependency injection perhaps). Or, make sure the Unity runtime is also accessible from the testing environment.

As coverage increases, feel free to also address any of the minor cleanup items listed here #2.

## Acceptance Criteria
- [ ] A unit testing runner should be selected (probably Unity Test Runner)
- [ ] A single test should be written to instantiate the `Quarters.cs` class
- [ ] Functions in the class should be tested & refactored as needed to allow for testability
- [ ] A readme should be created/edited to explain how to run tests

## Resources
- Unity docs on Unity Test Runner, which seems to be aimed at higher-level tests and not as much for unit testing https://unity.com/how-to/unity-test-framework-video-game-development
- How to use Unity Test Runner for unit testing https://medium.com/geekculture/doing-basic-unit-testing-in-unity-c-9de7f923d2ee
- Example .NET core project with XUnit set up for testing [here](https://github.com/bmcilw1/CsharpPokerFunctional)
- Unity testing basics https://www.raywenderlich.com/9454-introduction-to-unity-unit-testing
- Unity testing video https://www.youtube.com/watch?v=TyxDg70hc3g

**Comment by paulofer85** [comment]
Some advances I have made:
 - In `A unit testing runner should be selected (probably Unity Test Runner)`: I chose Visual Studio, It seems that `Unity Test Runner` it is just to review your test and not to write them or debug them:
![image](https://user-images.githubusercontent.com/3865131/169154449-bc251398-dcac-4415-b574-5bc0f2ab98e6.png)
- Right now I can reference to `QuartersSDK` and I'm working on intantiate it. I'm trying to instantiate it as `EditMode` maybe I should do it as `PlayMode` because I was not able to instantiate it.

**Comment by paulofer85** [comment]
I update the issue. We worked on the branch `unity-experiments` in a new .NET Core solution that shuould be imported into Unity. In this new solution you will be able to find:
- [x]  A unit testing runner should be selected (probably Unity Test Runner)
- [x]  A single test should be written to instantiate the Quarters.cs class
- [x]  Functions in the class should be tested & refactored as needed to allow for testability
- [x]  A readme should be created/edited to explain how to run tests

**Comment by bmcilw1** [comment]
completed on a branch
